# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

title: Continuing Education for Public Librarian Certification Record
description: null

issued: 2011-10-19
expires: 2016-10-19
certificate_no:

requirements: http://www.nysl.nysed.gov/libdev/cert/conted.htm